github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addComment: true
    addBadge: true
    addLabel: prebuilt-in-gitpod
image:
  file: .gitpod.Dockerfile
tasks:
  - init: pip3 install -r requirements.txt