github: 
  prebuilds: 
    addBadge: true
    addComment: true
    addLabel: prebuilt-in-gitpod
    branches: true
    master: true
    pullRequests: true
    pullRequestsFromForks: true
image: 
  file: .gitpod.Dockerfile
ports: 
  - port: 8080
tasks: 
  - init: "pip3 install -r requirements.txt"
  - command: redis-server
  - command: "opsdroid start"
