connectors:
  telegram:
    thinking-delay: 0
    token: $TELEGRAM_TOKEN
    typing-delay: 0
    whitelisted-users:
      - $TELEGRAM_WHITELIST_USER
  websocket:
    bot-name: chat0ps
    connection-timeout: 10
    max-connections: 10
databases:
  redis:
    host: localhost
logging:
  console: true
  extended: true
  level: debug
  path: /tmp/opsdroid.log
parsers:
  crontab:
    enabled: true
  regex:
    enabled: true
skills:
  - name: hi
    path: /workspace/chat0ps/skills/hi/
web:
  host: "127.0.0.1"
  port: 8080
  webhook-token: chat0ps
welcome-message: true
