apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb
  labels:
    app: chatops
    tier: backend
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: errbot
  labels:
    app: chatops
    tier: frontend
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    app: chatops
    tier: backend
spec:
  ports:
    - name: mongodb
      port: 27017
  selector:
    app: chatops
    tier: backend

---

apiVersion: v1
kind: Service
metadata:
  name: errbot
  labels:
    app: chatops
    tier: frontend
spec:
  ports:
    - name: http
      port: 80
  selector:
    app: chatops
    tier: frontend

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mongodb
  labels:
    app: chatops
    tier: backend
    version: "4.0"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: chatops
        tier: backend
        version: "4.0"
    spec:
      containers:
      - name: mongodb
        image: docker.io/mongo:4.0
        ports:
        - name: mongodb
          containerPort: 27017
        resources:
          requests:
            cpu: 256m
            memory: 512Mi
          limits:
            cpu: 1
            memory: 2Gi
        volumeMounts:
        - name: mongodb-data
          mountPath: /data/db
      volumes:
      - name: mongodb-data
        persistentVolumeClaim:
          claimName: mongodb

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: errbot
  labels:
    app: chatops
    tier: frontend
    version: "5.2.0"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: chatops
        tier: frontend
        version: "5.2.0"
    spec:
      containers:
      - name: errbot
        image: docker.io/boidacarapreta/errbot:latest
        ports:
        - name: http
          containerPort: 80
        resources:
          requests:
            cpu: 128m
            memory: 128Mi
          limits:
            cpu: 1
            memory: 512Mi
        volumeMounts:
        - name: errbot-config
          mountPath: /errbot/config.py
          subPath: config.py
          readOnly: true
        - name: errbot-data
          mountPath: /errbot/data
      volumes:
      - name: errbot-config
        secret:
          secretName: errbot
      - name: errbot-data
        persistentVolumeClaim:
          claimName: errbot
